import { IRegistrationMenuItem, TabId } from '@libs/registration-lib/types/interfaces/IRegistrationMenuItem';

export const tabs = (): IRegistrationMenuItem[] => [
  {
    id: TabId.IsRegistered,
    labelKey: 'registration.menu.isIndividualRegistered',
    titleKey: 'registration.menu.isIndividualRegistered',
    icon: '',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'isRegistered',
    helpLink: 'zendesk.registration.isRegistered',

  },
  {
    id: TabId.Privacy,
    labelKey: 'registration.menu.privacy',
    titleKey: 'registration.menu.privacy',
    icon: '',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'PrivacyStatement',
    helpLink: 'registration.zendesk.privacyStatement',
  },
  {
    id: TabId.PersonalInfo,
    labelKey: 'registration.menu.personal_info',
    titleKey: 'registration.menu.personal_info',
    icon: '',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'PersonalInformation',
    helpLink: 'zendesk.registration.personalInformation',
  },
  {
    id: TabId.Addresses,
    labelKey: 'registration.menu.addresses',
    titleKey: 'registration.menu.addresses',
    icon: '',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'Addresses',
    helpLink: 'zendesk.registration.addresses',
  },
  {
    id: TabId.AdditionalMembers,
    labelKey: 'registration.menu.household_members',
    titleKey: 'registration.menu.household_members',
    icon: '',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'AdditionalMembers',
    helpLink: 'registration.zendesk.householdmembers',
  },
  {
    id: TabId.Review,
    labelKey: 'registration.menu.review',
    titleKey: 'registration.menu.review',
    icon: '',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'ReviewRegistration',
    helpLink: 'zendesk.registration.review',
  },
  {
    id: TabId.Confirmation,
    labelKey: 'registration.menu.confirmation',
    titleKey: 'registration.page.confirmation',
    icon: '',
    disabled: true,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.print',
    nextButtonTextKey: 'registration.confirm_registration.label',
    componentName: 'ConfirmRegistration',
    helpLink: '',
  },
  {
    id: TabId.Assessment,
    labelKey: 'registration.menu.assessment',
    titleKey: 'registration.page.assessment',
    icon: '',
    disabled: true,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.print',
    nextButtonTextKey: 'registration.close_registration.label',
    componentName: 'ConfirmRegistration',
    helpLink: '',
  },
];
