trigger:
- feature/*
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Build-Defaults
- name: Patch
  value: $[counter(format('{0}.{1}',variables['Major'],variables['Minor']),0)]

name: $(Major).$(Minor).$(Patch)

resources: 
  repositories: 
  - repository: Templates
    name: 'Shared/pipeline-templates'
    type: git 
    ref: master

stages:
- template: stages/deploy-vue-stages.yml@Templates
  parameters:
    storage: $(WebAppStorage)
    packageFeed: $(PackageFeed-Npm)