trigger:
- master

pool:
  name: 'self-hosted-ubuntu-latest'

variables:
- group: Build-Defaults
- name: Patch
  value: $[counter(format('{0}.{1}',variables['Major'],variables['Minor']),0)]
- name: cdnEndpoint
  value: 'emis-cdne-emis'
- name: cdnProfile
  value: 'emis-cdnp-emis'

name: $(Major).$(Minor).$(Patch)

resources: 
  repositories: 
  - repository: Templates
    name: 'Shared/pipeline-templates'
    type: git 
    ref: master

stages:
- template: stages/deploy-vue-stages.yml@Templates
  parameters:
    storage: $(EmisWebAppStorage)
    packageFeed: $(PackageFeed-Npm)
    cdnEndpoint: $(cdnEndpoint)    
    cdnProfile: $(cdnProfile)