trigger:
- master

pool:
  name: 'self-hosted-ubuntu-latest'

variables:
- group: Build-Defaults
- name: Patch
  value: $[counter(format('{0}.{1}',variables['Major'],variables['Minor']),0)]

name: $(Major).$(Minor).$(Patch)

resources:
  repositories:
  - repository: Templates
    name: 'Shared/pipeline-templates'
    type: git
    ref: master

stages:
- template: stages/publish-npm-package-stages.yml@Templates
  parameters:
    packageFeed: $(PackageFeed-Npm)
    majorVersion: $(Major)
    minorVersion: $(Minor)
    patchVersion: $(Patch)