parameters:
  nodeJsVersion: ''
  disableCache: ''
  packageFeed: ''
  testCommand: ''
  appName: ''

stages:
  - stage: 'AcceptanceTest'
    displayName: 'Acceptance Stage'
    pool:
      vmImage: 'windows-2022'
    jobs:
      - template: '../jobs/acceptance-tests-azure-jobs.yml'
        parameters:
          nodeJsVersion: ${{ parameters.nodeJsVersion }}
          disableCache: ${{ parameters.disableCache }}
          packageFeed: ${{ parameters.packageFeed }}
          testCommand: ${{ parameters.testCommand }}
          appName: ${{ parameters.appName }}
