parameters:
  packageFeed: ''
  buildCommand: 'build --mode production'
  lokaliseCommand: 'lokalise --mode production'
  workingDir: ''
  nodeJsVersion: ''
  appVersion: ''
  disableCache: ''

stages:
  - stage: 'Build_Stage'
    displayName: 'Build'
    jobs:
      - job: 'Build_Web_App'
        displayName: 'Build application'
        steps:
          - template: '../steps/build-vue-steps.yml'
            parameters:
              packageFeed: ${{ parameters.packageFeed }}
              lokaliseCommand: ${{ parameters.lokaliseCommand }}
              buildCommand: ${{ parameters.buildCommand }}
              workingDir:  ${{ parameters.workingDir }}
              nodeJsVersion:  ${{ parameters.nodeJsVersion }}
              appVersion: ${{ parameters.appVersion }}
              disableCache: ${{ parameters.disableCache }}

          - publish: ${{ parameters.distDir }}
            artifact: dist
            displayName: "Publish Artifact"
