parameters:
  appName: ''
  packageFeed: ''
  lokalise: true
  lint: true
  distDir: 'dist'
  buildCommand: 'build --mode production'
  lokaliseCommand: 'lokalise --mode production'
  workingDir: ''
  isPullRequest: ''

stages:
  - stage: 'Build Stage'
    jobs:
      - job: 'Build Web App'
        steps:
          - template: '../steps/build-vue-steps.yml'
            parameters:
              appName: ${{ parameters.appName }}
              packageFeed: ${{ parameters.packageFeed }}
              lokalise: ${{ parameters.lokalise }}
              lint: ${{ parameters.lint }}
              buildCommand: ${{ parameters.buildCommand }}
              lokaliseCommand: ${{ parameters.lokaliseCommand }}
              workingDir:  ${{ parameters.workingDir }}
              isPullRequest:  ${{ parameters.isPullRequest }}

          - publish: ${{ parameters.distDir }}
            artifact: dist
            displayName: "Publish Artifact"
