parameters:
  packageFeed: ''
  buildCommand: 'build --mode production'
  lokaliseCommand: 'lokalise --mode production'
  workingDir: ''
  nodeJsVersion: ''
  appVersion: ''

stages:
  - stage: 'Build_Stage'
    displayName: 'Build'
    jobs:
      - job: 'Build_Web_App'
        variables:
          - group: Script
        displayName: 'Build application'
        steps:
          - powershell: |
              $branchId = '$(System.PullRequest.SourceBranch)'.Split('/')[3]
              echo "Branch id is:" $branchId
              Write-Host "##vso[task.setvariable variable=VITE_TEMP_BRANCH_ID]$branchId"
            displayName: 'Set TEMP_BRANCH_ID'
            condition: eq(variables['Build.Reason'], 'PullRequest')
          
          - template: '../steps/build-vue-steps.yml'
            parameters:
              packageFeed: ${{ parameters.packageFeed }}
              lokaliseCommand: ${{ parameters.lokaliseCommand }}
              buildCommand: ${{ parameters.buildCommand }}
              workingDir:  ${{ parameters.workingDir }}
              nodeJsVersion:  ${{ parameters.nodeJsVersion }}
              appVersion: ${{ parameters.appVersion }}

          - publish: ${{ parameters.distDir }}
            artifact: dist
            displayName: "Publish Artifact"
