parameters:
  storage: ""
  cdnEndpoint: ""
  cdnProfile: ""

stages:
  - stage: "Deploy_to_Prod"
    displayName: "Deploy to Prod"
    dependsOn:
      - TestValidationStage
    condition: |
      in(dependencies.TestValidationStage.result, 'Succeeded')
    jobs:
      - deployment: "Deploy_WebApp_Prod"
        displayName: "Deploy WebApp to Prod"
        environment: "Prod-UI"
        variables:
          - group: Env-Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - template: "../steps/deploy-steps.yml"
                  parameters:
                    storage: ${{ parameters.storage }}
                    cdnEndpoint: ${{ parameters.cdnEndpoint }}
                    cdnProfile: ${{ parameters.cdnProfile }}
                    azureSubscription: "CRC Tech Prod"

  - stage: "Deploy_to_Prod_Manual"
    displayName: "Deploy to Prod (manual)"
    dependsOn:
      - TestValidationStage
    condition: |
      in(dependencies.TestValidationStage.result, 'Failed', 'Canceled')
    jobs:
      - deployment: "Deploy_WebApp_Prod_Manual"
        displayName: "Deploy WebApp to Prod"
        environment: "Prod-UI-Gate"
        variables:
          - group: Env-Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - template: "../steps/deploy-steps.yml"
                  parameters:
                    storage: ${{ parameters.storage }}
                    cdnEndpoint: ${{ parameters.cdnEndpoint }}
                    cdnProfile: ${{ parameters.cdnProfile }}
                    azureSubscription: "CRC Tech Prod"
