parameters:
  appName: ''
  packageFeed: ''
  storage: ''
  cdnEndpoint: ''
  cdnProfile: ''
  lokalise: true
  lint: true
  buildCommand: 'build --mode production'
  lokaliseCommand: 'lokalise --mode production'
  workingDir: ''
  distDir: ''
  isPullRequest: ''

stages:

  - stage: 'Feature_Name_Policy'
    displayName: 'Feature Name Policy'
    jobs:
      - job: Feature_Name_Policy
        condition: and(succeeded(), startsWith(variables['build.reason'], 'PullRequest'))
        steps:
          - task: PowerShell@2
            displayName: 'Feature Name Policy'
            inputs:
              targetType: 'inline'
              script: |
                $conforms = '$(System.PullRequest.SourceBranch)' -match 'refs/heads/feature/\d{2,}'
                if (-not $conforms){
                  throw "Branch name must follow feature/#### format.  Branch was $(System.PullRequest.SourceBranch)"
                }
                echo "The feature branch $(System.PullRequest.SourceBranch) follows the name policy"
      - job: 'Store_version'
        displayName: 'Store version'
        steps:
          - task: PowerShell@2
            displayName: 'Store version'
            inputs:
              targetType: 'inline'
              script: |
                $version = "$(Build.BuildNumber)"
                echo "Version is $version, Build number is $(Build.BuildNumber)"
                echo "##vso[task.setvariable variable=VUE_APP_VERSION]$(Build.BuildNumber)"


  - template: './build-vue-stage.yml'
    parameters:
      appName: ${{ parameters.appName }}
      packageFeed: ${{ parameters.packageFeed }}
      lokalise: ${{ parameters.lokalise }}
      lint: ${{ parameters.lint }}
      buildCommand: ${{ parameters.buildCommand }}
      lokaliseCommand: ${{ parameters.lokaliseCommand }}
      workingDir: ${{ parameters.workingDir }}
      distDir: ${{ parameters.distDir }}
      isPullRequest: ${{ parameters.isPullRequest }}


  - template: './deploy-webapp-stage.yml'
    parameters:
      appName: ${{ parameters.appName }}
      storage: ${{ parameters.storage }}
      cdnEndpoint: ${{ parameters.cdnEndpoint }}
      cdnProfile: ${{ parameters.cdnProfile }}
      packageFeed: ${{ parameters.packageFeed }} # Need until we need to install npm before testing
      isPullRequest: ${{ parameters.isPullRequest }}

