parameters:
  storage: ''
  cdnEndpoint: ''
  cdnProfile: ''

stages:
  - stage: 'Deploy_to_Dev'
    displayName: 'Deploy to Dev'
    dependsOn: 'E2E_Test_Stage'
    condition: succeeded()
    pool:
      vmImage: 'windows-2022'
    jobs:
      - deployment: 'Deploy_WebApp_Dev'
        displayName: 'Deploy WebApp to Dev'
        environment: 'Dev'
        variables:
          - group: Env-Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: '../steps/deploy-steps.yml'
                  parameters:
                    storage: ${{ parameters.storage }}
                    cdnEndpoint: ${{ parameters.cdnEndpoint }}
                    cdnProfile: ${{ parameters.cdnProfile }}
                    azureSubscription: 'CRC Tech Dev'
