parameters:
  - name: resource_group_front_door
    type: string
    default: 'front-door-leo'
  - name: azure_front_door_name
    type: string
    default: 'fd-emis'
  - name: storage_account_name_blue
    type: string
    default: 'fdbluestorage'
  - name: storage_account_name_green
    type: string
    default: 'fdgreenstorage'
  - name: backendPoolName
    type: string
    default: 'storage-accounts'
  - name: backend_address_blue
    type: string
    default: 'fdbluestorage.z9.web.core.windows.net'
  - name: backend_address_green
    type: string
    default: 'fdgreenstorage.z9.web.core.windows.net'
  - name: azureSubscription
    type: string
    default: 'CRC Tech Dev'

stages:
  - stage: deploy_and_switch_traffic
    condition: succeeded()
    variables:
      active_environment: $[ if(int(replace(variables['Build.BuildNumber'], '.', '')) % 2 == 0, 'blue', 'green')
      # The above expression switches the active_environment parameter between 'blue' and 'green' based on the parity of the build number.
    pool:
      vmImage: 'windows-2022'
    displayName: 'Blue/Green Deployment'
    jobs:
      - job: deploy
        displayName: 'Deploy'
        steps:
          - task: AzureFileCopy@4
            displayName: 'Upload static app to Azure Blob Storage - Blue'
            condition: eq('${{ parameters.active_environment }}', 'blue')
            inputs:
              SourcePath: '$(Pipeline.Workspace)/dist'
              Destination: 'AzureBlob'
              azureSubscription: '${{ parameters.azureSubscription }}'
              ContainerName: '$web'
              CleanTargetBeforeCopy: true
              storage: '${{ parameters.storage_account_name_blue }}'
          - task: AzureFileCopy@4
            displayName: 'Upload static app to Azure Blob Storage - Green'
            condition: eq('${{ parameters.active_environment }}', 'green')
            inputs:
              SourcePath: '$(Pipeline.Workspace)/dist'
              Destination: 'AzureBlob'
              azureSubscription: '${{ parameters.azureSubscription }}'
              ContainerName: '$web'
              CleanTargetBeforeCopy: true
              storage: '${{ parameters.storage_account_name_green }}'

      - job: switch_traffic
        dependsOn: deploy
        displayName: 'Switch traffic'
        steps:
          - task: AzureCLI@2
            displayName: 'Update backends priorities'
            inputs:
              azureSubscription: '${{ parameters.azureSubscription }}'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az network front-door backend-pool update \
                  --front-door-name ${{ parameters.azure_front_door_name }} \
                  --resource-group ${{ parameters.resource_group_front_door }} \
                  --name '${{ parameters.backendPoolName }}' \
                  --set "backends[?address=='${{ parameters.backend_address_blue }}'].priority=$([[ '${{ parameters.active_environment }}' == 'blue' ]] && echo 1 || echo 2)" \
                  --set "backends[?address=='${{ parameters.backend_address_green }}'].priority=$([[ '${{ parameters.active_environment }}' == 'green' ]] && echo 1 || echo 2)"
