parameters:
  appName: ''
  packageFeed: ''
  storage: ''
  cdnEndpoint: ''
  cdnProfile: ''
  lokalise: true
  lint: true
  buildCommand: 'build --mode production'
  lokaliseCommand: 'lokalise --mode production'
  workingDir: ''
  distDir: ''
  isPullRequest: ''

stages:

  - template: './feature-name-policy-stage.yml'
  
  - template: './build-vue-stage.yml'
    parameters:
      appName: ${{ parameters.appName }}
      packageFeed: ${{ parameters.packageFeed }}
      lokalise: ${{ parameters.lokalise }}
      lint: ${{ parameters.lint }}
      buildCommand: ${{ parameters.buildCommand }}
      lokaliseCommand: ${{ parameters.lokaliseCommand }}
      workingDir: ${{ parameters.workingDir }}
      distDir: ${{ parameters.distDir }}
      isPullRequest: ${{ parameters.isPullRequest }}


  - template: './deploy-webapp-stage.yml'
    parameters:
      appName: ${{ parameters.appName }}
      storage: ${{ parameters.storage }}
      cdnEndpoint: ${{ parameters.cdnEndpoint }}
      cdnProfile: ${{ parameters.cdnProfile }}
      packageFeed: ${{ parameters.packageFeed }} # Need until we need to install npm before testing
      isPullRequest: ${{ parameters.isPullRequest }}

