stages:
  - stage: deploy_and_switch_traffic
    condition: succeeded()
    variables:
      frontDoorResourceGroup: 'front-door-leo'
      frontDoorName: 'fd-emis'
      frontDoorUrl: 'fd-leo.crc-tech.ca'
      frontDoorBackendPoolName: 'storage-accounts'
      backendBlueHostName: 'blue-app.azureedge.net'
      backendGreenHostName: 'green-app.azureedge.net'
      storageAccountBlueName: 'tfblue'
      storageAccountGreenName: 'tfgreen'
      targetBackendHostName: '' # Set in line script
      targetStorageAccountName: '' # Set in inline script
      targetWebAppUrl: '' # Set in toggle script
    pool:
      vmImage: 'windows-2022'
    displayName: 'Blue/Green Deployment'
    jobs:
      - job: Deploy
        displayName: 'Deploy'
        steps:
          - powershell: |
              $response = Invoke-WebRequest "$(frontDoorUrl)" -UseBasicParsing -Method Head
              $targetBackendHostName= If ($response.Headers["active-env"] -like "blue-app") {"$(backendGreenHostName)"} Else {"$(backendBlueHostName)"}
              $targetStorageAccountName= If ($response.Headers["active-env"] -like "blue-app") {"$(storageAccountGreenName)"} Else {"$(storageAccountBlueName)"}
              Write-Host "##vso[task.setvariable variable=targetBackendHostName]$targetBackendHostName"
              Write-Host "##vso[task.setvariable variable=targetStorageAccountName]$targetStorageAccountName"
              Write-Host "Target backend host name: $targetStorageAccountName"
            displayName: "Detect target storage account for deployment"

          - task: AzureCLI@2
            displayName: 'Clean target storage account'
            inputs:
              azureSubscription: 'CRC Tech Dev'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage blob delete-batch --source '$web' --account-name '$(targetStorageAccountName)'

          - task: AzureFileCopy@3
            displayName: 'Upload to target storage account'
            inputs:
              sourcePath: '$(Pipeline.Workspace)/dist/$(targetStorageAccountName)'
              azureSubscription: 'CRC Tech Dev'
              destination: 'AzureBlob'
              storage: '$(targetStorageAccountName)'
              containerName: '$web'

          - task: AzurePowerShell@4
            displayName: 'Switch environments Blue/Green using Frontdoor Azure CLI'
            inputs:
              azureSubscription: 'CRC Tech Dev'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/tools/pipelines/switch-storage.ps1'
              ScriptArguments: '-frontDoorResourceGroup $(frontDoorResourceGroup) -frontDoorName $(frontDoorName) -frontDoorBackendPoolName $(frontDoorBackendPoolName) -frontDoorUrl $(frontDoorUrl) -backendStorageBlue $(backendStorageBlue) -backendStorageGreen $(backendStorageGreen)'
              azurePowerShellVersion: 'LatestVersion'
