parameters:
  - name: frontDoorResourceGroup
    type: string
    default: 'front-door-leo'
  - name: frontDoorName
    type: string
    default: 'fd-emis'
  - name: frontDoorUrl
    type: string
    default: 'https://fd-leo.crc-tech.ca/'
  - name: frontDoorBackendPoolName
    type: string
    default: 'storage-accounts'
  - name: backendStorageBlue
    type: string
    default: 'green-blue.azureedge.net'
  - name: backendStorageGreen
    type: string
    default: 'green-app.azureedge.net'
  - name: azureSubscription
    type: string
    default: 'CRC Tech Dev'

stages:
  - stage: deploy_and_switch_traffic
    condition: succeeded()
    pool:
      vmImage: 'windows-2022'
    displayName: 'Blue/Green Deployment'
    jobs:
      - job: Deploy
        displayName: 'Deploy'
        steps:
          - powershell: |
              $response = Invoke-WebRequest "$(frontDoorUrl)" -UseBasicParsing -Method Head
              $targetStorageAccountName= If ($response.Headers["active-env"] -like "blue-app") {"$(appServiceNameBlue)"} Else {"$(appServiceNameGreen)"}
              Write-Host "##vso[task.setvariable variable=targetStorageAccountName]$targetStorageAccountName"
              Write-Host "Target Storage Account Name for deployment: $targetStorageAccountName"
              displayName: "Detect target environment color for deployment"

          - task: AzureCLI@2
            displayName: 'Clean Target Storage'
            inputs:
              azureSubscription: '${{ parameters.azureSubscription }}'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage blob delete-batch --source '$web' --account-name '$(targetStorageAccountName)'

          - task: AzureFileCopy@3
            condition: eq(variables['targetStorageAccountName'], 'blue')
            displayName: 'Upload to Azure Storage Blue'
            inputs:
              sourcePath: '$(Pipeline.Workspace)/dist/blue'
              azureSubscription: '${{ parameters.azureSubscription }}'
              destination: 'AzureBlob'
              storage: '$(targetStorageAccountName)'
              containerName: '$web'

          - task: AzureFileCopy@3
            condition: eq(variables['targetStorageAccountName'], 'green')
            displayName: 'Upload to Azure Storage Green'
            inputs:
              sourcePath: '$(Pipeline.Workspace)/dist/green'
              azureSubscription: '${{ parameters.azureSubscription }}'
              destination: 'AzureBlob'
              storage: '$(targetStorageAccountName)'
              containerName: '$web'

          - task: AzurePowerShell@4
            displayName: 'Switch environments Blue/Green using Frontdoor Azure CLI'
            inputs:
              azureSubscription: '${{ parameters.azureSubscription }}'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/tools/pipelines/switch-storage.ps1'
              ScriptArguments: '-frontDoorResourceGroup $(frontDoorResourceGroup) -frontDoorName $(frontDoorName) -frontDoorBackendPoolName $(frontDoorBackendPoolName) -frontDoorUrl $(frontDoorUrl) -backendStorageBlue $(backendStorageBlue) -backendStorageGreen $(backendStorageGreen)'
              azurePowerShellVersion: 'LatestVersion'
