parameters:
  workingDir: ''
  testsDir: '' # The folder containing all tests we want to run


stages:
  - stage: DetermineCypressTestsStage
    displayName: 'Determine Cypress Tests'
    jobs:
      - job: DetermineCypressTestsJob
        displayName: 'Determine cypress tests to run'
        steps:
          - checkout: 'self'
            submodules: 'true'
            fetchDepth: 0
            persistCredentials: true
          - script: |
              # In the context of pull requests, or after code is merge
              if [ "$(Build.Reason)" != "Schedule" ] && [ "$(Build.Reason)" != "Manual" ]; then
                 # We take the current working director and remove ./
                 WORKING_DIR=$(echo "${{ parameters.workingDir }}" | sed 's/^\.\///')
              
                 # Get the list of affected Cypress tests files compared to master
                 # Remove working director from the path
                 # Put multiline on the same line separated by a comma
                 AFFECTED_TESTS=$(git diff --name-only --diff-filter=AMR HEAD^1 HEAD | grep -E '.*\.cy\.ts$' | sed "s|$WORKING_DIR||" | tr '\n' ',')
                 # Remove last , 
                 AFFECTED_TESTS=${AFFECTED_TESTS%?}
                 echo "The following test will be run:"
                 echo "$AFFECTED_TESTS"
                # Will only test changed tests
                echo "##vso[task.setvariable variable=affectedTests;isOutput=true]$AFFECTED_TESTS"
              else
                # Will run all tests contained in testDir when triggered by a schedule job or manually
                echo "All tests contained in ${{parameters.testsDir}} will be run"
                echo "##vso[task.setvariable variable=affectedTests;isOutput=true]${{parameters.testsDir}}"
              fi
            name: getCypressTests
            displayName: 'Generate cypress spec parameter'
