parameters:
  packageFeed: ''
  nodeJsVersion: ''
  disableCache: ''
  runTests: false
  distDir: ''
  workingDir: ''

stages:
  - stage: 'E2E_Test_Stage'
    condition: and(succeeded(), eq('${{ parameters.runTests }}', true))
    displayName: 'E2E Tests'
    jobs:
      - job: Cypress
        displayName: 'Critical path tests'
        variables:
          - group: Env-Dev
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          parallel: 2
        steps:
          - template: '../steps/cypress-steps.yml'
            parameters:
              packageFeed: ${{ parameters.packageFeed }}
              nodeJsVersion: ${{ parameters.nodeJsVersion }}
              disableCache: ${{ parameters.disableCache }}
              distDir: ${{ parameters.distDir }}
              workingDir: ${{ parameters.workingDir }}
