parameters:
  packageFeed: ''
  nodeJsVersion: ''
  runTests: false
  distDir: ''
  workingDir: ''

stages:
  - stage: 'E2E_Test_Stage'
    condition: and(succeeded(), eq('${{ parameters.runTests }}', true))
    displayName: 'E2E Tests'
    jobs:
      - template: '../jobs/smoke-tests-job.yml'
        parameters:
          packageFeed: ${{ parameters.packageFeed }}
          nodeJsVersion: ${{ parameters.nodeJsVersion }}
          distDir: ${{ parameters.distDir }}
          workingDir: ${{ parameters.workingDir }}
