parameters:
  appName: ''
  packageFeed: ''
  isPullRequest: ''

stages:
  - stage: 'Post_Build_Stage'
    displayName: 'Post Build'
    condition: succeeded()
    jobs:
      - job: 'Test'
        strategy:
          parallel: 2
        displayName: 'Test affected packages'
        steps:
          - template: '../steps/cache-install-npm.yml'
            parameters:
              packageFeed: ${{ parameters.packageFeed }}

          - script: yarn test:parallel ${{parameters.isPullRequest}} ${{parameters.appName}} $(System.TotalJobsInPhase) $(System.JobPositionInPhase)
            displayName: 'Run tests'

  - ${{ if eq( variables['build.sourceBranch'], 'refs/heads/master') }}:
      - job: 'Publish_Test'
        dependsOn: 'Test'
        displayName: 'Publish Results & Coverage'
        steps:
          - task: PublishTestResults@2
            displayName: 'Publish Test Result'
            condition: succeededOrFailed()
            inputs:
              testRunner: VSTest
              testResultsFiles: '**/*result*.trx'
              failTaskOnFailedTests: false

          - template: '../steps/cache-install-npm.yml'
            parameters:
              packageFeed: ${{ parameters.packageFeed }}

          - script: node ./tools/scripts/merge-test-coverage.js
            displayName: 'Merge Code Coverage Reports'
            condition: succeededOrFailed()

          - task: PublishCodeCoverageResults@1
            displayName: 'Publish Merged Code Coverage Report'
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(Build.SourcesDirectory)/coverage/merged-cobertura-coverage.xml'
              failIfCoverageEmpty: false
