parameters:
  appName: ''
  packageFeed: ''
  isPullRequest: ''

stages:
  - stage: 'Post_Build_Stage'
    displayName: 'Post Build'
    condition: succeeded()
    jobs:
      - job: 'Test'
        displayName: 'Test affected packages'
        steps:
          - task: Cache@2
            displayName: Cache yarn packages
            inputs:
              key: '"$(Agent.OS)" | **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock'
              path: $(Build.SourcesDirectory)/node_modules
              cacheHitVar: CACHE_HIT

          - task: Yarn@3
            displayName: 'Install yarn packages'
            condition: ne(variables['CACHE_HIT'], 'true')
            inputs:
              customRegistry: 'useFeed'
              customFeed: ${{ parameters.packageFeed }}
              arguments: --frozen-lockfile

          - script: node ./tools/scripts/run-commands.js coverage ${{parameters.isPullRequest}} ${{parameters.appName}}
            displayName: 'Run tests'

      - job: 'Publish_Test'
        dependsOn: 'Test'
        displayName: 'Publish Results'
        steps:
          - task: PublishTestResults@2
            displayName: 'Publish Test Result'
            condition: and(succeededOrFailed(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
            inputs:
              testRunner: VSTest
              testResultsFiles: '**/*result*.trx'
              failTaskOnFailedTests: false

          - script: node ./tools/scripts/merge-test-coverage.js
            displayName: 'Merge Code Coverage Reports'
            condition: and(succeededOrFailed(), eq(variables['build.sourceBranch'], 'refs/heads/master'))

          - task: PublishCodeCoverageResults@1
            displayName: 'Publish Merged Code Coverage Report'
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(Build.SourcesDirectory)/coverage/merged-cobertura-coverage.xml'
              failIfCoverageEmpty: false
            condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
