/* eslint-disable */
import {
  QueryType, ReportingTopic, IQuery,
} from '@libs/entities-lib/reporting';


export const UsersL5En = {
  id: 'UsersL5',
  queryType: QueryType.StandardL5en,
  topic: ReportingTopic.UsersInTeams,
  state: "{\"columns\":[{\"visibleIndex\":13,\"dataField\":\"teamDetail.id\",\"name\":\"teamDetail.id\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":12,\"dataField\":\"teamDetail.isActive\",\"name\":\"teamDetail.isActive\",\"dataType\":\"boolean\",\"visible\":false},{\"visibleIndex\":17,\"dataField\":\"teamDetail.name\",\"name\":\"teamDetail.name\",\"dataType\":\"string\",\"visible\":true},{\"visibleIndex\":18,\"dataField\":\"teamDetail.primaryContact\",\"name\":\"teamDetail.primaryContact\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":6,\"dataField\":\"userAccount.accessLevelNameEn\",\"name\":\"userAccount.accessLevelNameEn\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":7,\"dataField\":\"userAccount.accessLevelNameFr\",\"name\":\"userAccount.accessLevelNameFr\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":1,\"dataField\":\"userAccount.createDate\",\"name\":\"userAccount.createDate\",\"dataType\":\"datetime\",\"visible\":false},{\"visibleIndex\":0,\"dataField\":\"userAccount.displayName\",\"name\":\"userAccount.displayName\",\"dataType\":\"string\",\"visible\":true,\"sortOrder\":\"asc\",\"sortIndex\":0},{\"visibleIndex\":14,\"dataField\":\"userAccount.emailAddress\",\"name\":\"userAccount.emailAddress\",\"dataType\":\"string\",\"visible\":true},{\"visibleIndex\":11,\"dataField\":\"userAccount.givenName\",\"name\":\"userAccount.givenName\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":3,\"dataField\":\"userAccount.id\",\"name\":\"userAccount.id\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":4,\"dataField\":\"userAccount.isInactive\",\"name\":\"userAccount.isInactive\",\"dataType\":\"boolean\",\"visible\":false},{\"visibleIndex\":9,\"dataField\":\"userAccount.phoneNumber\",\"name\":\"userAccount.phoneNumber\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":5,\"dataField\":\"userAccount.preferredLanguage\",\"name\":\"userAccount.preferredLanguage\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":15,\"dataField\":\"userAccount.roleNameEn\",\"name\":\"userAccount.roleNameEn\",\"dataType\":\"string\",\"visible\":true},{\"visibleIndex\":16,\"dataField\":\"userAccount.roleNameFr\",\"name\":\"userAccount.roleNameFr\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":8,\"dataField\":\"userAccount.surname\",\"name\":\"userAccount.surname\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":2,\"dataField\":\"userAccount.updateDate\",\"name\":\"userAccount.updateDate\",\"dataType\":\"datetime\",\"visible\":false},{\"visibleIndex\":10,\"dataField\":\"userAccount.userPrincipalName\",\"name\":\"userAccount.userPrincipalName\",\"dataType\":\"string\",\"visible\":false}],\"allowedPageSizes\":[10,20,40],\"filterPanel\":{\"filterEnabled\":true},\"filterValue\":null,\"searchText\":\"\",\"pageIndex\":0,\"pageSize\":20}",
  name: 'User list',
} as IQuery;


export const UsersL5Fr = {
  id: 'UsersL5',
  queryType: QueryType.StandardL5fr,
  topic: ReportingTopic.UsersInTeams,
  state: "{\"columns\":[{\"visibleIndex\":14,\"dataField\":\"teamDetail.id\",\"name\":\"teamDetail.id\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":13,\"dataField\":\"teamDetail.isActive\",\"name\":\"teamDetail.isActive\",\"dataType\":\"boolean\",\"visible\":false},{\"visibleIndex\":17,\"dataField\":\"teamDetail.name\",\"name\":\"teamDetail.name\",\"dataType\":\"string\",\"visible\":true},{\"visibleIndex\":18,\"dataField\":\"teamDetail.primaryContact\",\"name\":\"teamDetail.primaryContact\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":6,\"dataField\":\"userAccount.accessLevelNameEn\",\"name\":\"userAccount.accessLevelNameEn\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":7,\"dataField\":\"userAccount.accessLevelNameFr\",\"name\":\"userAccount.accessLevelNameFr\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":1,\"dataField\":\"userAccount.createDate\",\"name\":\"userAccount.createDate\",\"dataType\":\"datetime\",\"visible\":false},{\"visibleIndex\":0,\"dataField\":\"userAccount.displayName\",\"name\":\"userAccount.displayName\",\"dataType\":\"string\",\"visible\":true,\"sortOrder\":\"asc\",\"sortIndex\":0},{\"visibleIndex\":15,\"dataField\":\"userAccount.emailAddress\",\"name\":\"userAccount.emailAddress\",\"dataType\":\"string\",\"visible\":true},{\"visibleIndex\":11,\"dataField\":\"userAccount.givenName\",\"name\":\"userAccount.givenName\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":3,\"dataField\":\"userAccount.id\",\"name\":\"userAccount.id\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":4,\"dataField\":\"userAccount.isInactive\",\"name\":\"userAccount.isInactive\",\"dataType\":\"boolean\",\"visible\":false},{\"visibleIndex\":9,\"dataField\":\"userAccount.phoneNumber\",\"name\":\"userAccount.phoneNumber\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":5,\"dataField\":\"userAccount.preferredLanguage\",\"name\":\"userAccount.preferredLanguage\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":12,\"dataField\":\"userAccount.roleNameEn\",\"name\":\"userAccount.roleNameEn\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":16,\"dataField\":\"userAccount.roleNameFr\",\"name\":\"userAccount.roleNameFr\",\"dataType\":\"string\",\"visible\":true},{\"visibleIndex\":8,\"dataField\":\"userAccount.surname\",\"name\":\"userAccount.surname\",\"dataType\":\"string\",\"visible\":false},{\"visibleIndex\":2,\"dataField\":\"userAccount.updateDate\",\"name\":\"userAccount.updateDate\",\"dataType\":\"datetime\",\"visible\":false},{\"visibleIndex\":10,\"dataField\":\"userAccount.userPrincipalName\",\"name\":\"userAccount.userPrincipalName\",\"dataType\":\"string\",\"visible\":false}],\"allowedPageSizes\":[10,20,40],\"filterPanel\":{\"filterEnabled\":true},\"filterValue\":null,\"searchText\":\"\",\"pageIndex\":0,\"pageSize\":20}",
  name: 'Liste d\'usagers',
} as IQuery;