parameters:
  packageFeed: ''
  lokalise: true
  buildCommand: 'build --mode production'
  lokaliseCommand: 'lokalise --mode production'
  workingDir: ''
  distDir: ''
  nodeJsVersion: ''
  appVersion: ''
  disableCache: ''

stages:
  # Build the application and publish the artifact
  - ${{ if eq( variables['build.reason'], 'PullRequest') }}:
    - template: './stages/build-stage.yml'
      parameters:
        packageFeed: ${{ parameters.packageFeed }}
        lokalise: ${{ parameters.lokalise }}
        lokaliseCommand: ${{ parameters.lokaliseCommand }}
        buildCommand: ${{ parameters.buildCommand }}
        workingDir: ${{ parameters.workingDir }}
        distDir: ${{ parameters.distDir }}
        nodeJsVersion: ${{ parameters.nodeJsVersion }}
        appVersion: ${{ parameters.appVersion }}
        disableCache: ${{ parameters.disableCache }}

  # Run E2E Tests
  - ${{ if eq( variables['build.reason'], 'PullRequest') }}:
    - template: './stages/e2e-tests-stage.yml'
      parameters:
        packageFeed: ${{ parameters.packageFeed }}
        nodeJsVersion: ${{ parameters.nodeJsVersion }}
        disableCache: ${{ parameters.disableCache }}
        workingDir: ${{ parameters.workingDir }}
        distDir: ${{ parameters.distDir }}

