parameters:
  packageFeed: ''
  lokalise: true
  buildCommand: 'build --mode production'
  lokaliseCommand: 'lokalise --mode production'
  workingDir: ''
  distDir: ''
  nodeJsVersion: ''
  appVersion: ''
  disableCache: ''
  runE2EStage: true

stages:
  # Build the application and publish the artifact
  - template: './stages/build-stage.yml'
    parameters:
      packageFeed: ${{ parameters.packageFeed }}
      lokalise: ${{ parameters.lokalise }}
      lokaliseCommand: ${{ parameters.lokaliseCommand }}
      buildCommand: ${{ parameters.buildCommand }}
      workingDir: ${{ parameters.workingDir }}
      distDir: ${{ parameters.distDir }}
      nodeJsVersion: ${{ parameters.nodeJsVersion }}
      appVersion: ${{ parameters.appVersion }}
      disableCache: ${{ parameters.disableCache }}

  # Run E2E Tests
  - ${{ if eq( variables['build.reason'], 'PullRequest') }}:
    - stage: 'E2E_Test_Stage'
      condition: and(succeeded(), eq('${{ parameters.runE2EStage }}', true))
      displayName: 'E2E Tests'
      jobs:
        - template: './jobs/e2e-tests-job.yml'
          parameters:
            packageFeed: ${{ parameters.packageFeed }}
            nodeJsVersion: ${{ parameters.nodeJsVersion }}
            disableCache: ${{ parameters.disableCache }}
            distDir: ${{ parameters.distDir }}
            workingDir: ${{ parameters.workingDir }}

