parameters:
  appName: ''
  packageFeed: ''
  storage: ''
  cdnEndpoint: ''
  cdnProfile: ''
  lokalise: true
  buildCommand: 'build --mode production'
  lokaliseCommand: 'lokalise --mode production'
  workingDir: ''
  distDir: ''
  isPullRequest: ''
  nodeJsVersion: ''
  appVersion: ''
  disableCache: ''
  runE2EStage: false

stages:

  # Trigger before the build
  - template: './stages/pre-build-stage.yml'

  # Build the application and publish the artifact
  - template: './stages/build-stage.yml'
    parameters:
      packageFeed: ${{ parameters.packageFeed }}
      lokalise: ${{ parameters.lokalise }}
      lokaliseCommand: ${{ parameters.lokaliseCommand }}
      buildCommand: ${{ parameters.buildCommand }}
      workingDir: ${{ parameters.workingDir }}
      distDir: ${{ parameters.distDir }}
      nodeJsVersion: ${{ parameters.nodeJsVersion }}
      appVersion: ${{ parameters.appVersion }}
      disableCache: ${{ parameters.disableCache }}

  # Run unit tests & component tests
  - template: './stages/tests-stage.yml'
    parameters:
      appName: ${{ parameters.appName }}
      packageFeed: ${{ parameters.packageFeed }}
      isPullRequest: ${{ parameters.isPullRequest }}
      nodeJsVersion: ${{ parameters.nodeJsVersion }}
      disableCache: ${{ parameters.disableCache }}
      workingDir: ${{ parameters.workingDir }}
      distDir: ${{ parameters.distDir }}

  # Run E2E Tests
  - stage: 'E2E_Test_Stage'
    condition: and(succeeded(), eq('${{ parameters.runE2EStage }}', true))
    displayName: 'E2E Tests'
    jobs:
      - template: './jobs/smoke-tests-job.yml'
        parameters:
          packageFeed: ${{ parameters.packageFeed }}
          nodeJsVersion: ${{ parameters.nodeJsVersion }}
          disableCache: ${{ parameters.disableCache }}
          distDir: ${{ parameters.distDir }}
          workingDir: ${{ parameters.workingDir }}

  # Deploy to temporary environment for manual testing
  - ${{ if eq( variables['build.reason'], 'PullRequest') }}:
    - template: './stages/deploy-to-temporary-url-stage.yml'
      parameters:
        cdnEndpoint: ${{ parameters.cdnEndpoint }}
        cdnProfile: ${{ parameters.cdnProfile }}

  # Deploy to DEV
  - ${{ if eq( variables['build.sourceBranch'], 'refs/heads/master') }}:
    - template: './stages/deploy-to-dev-stage.yml'
      parameters:
        storage: ${{ parameters.storage }}
        cdnEndpoint: ${{ parameters.cdnEndpoint }}
        cdnProfile: ${{ parameters.cdnProfile }}

  # Deploy to LAB
  - ${{ if eq( variables['build.sourceBranch'], 'refs/heads/master') }}:
    - template: './stages/deploy-to-lab-stage.yml'
      parameters:
        storage: ${{ parameters.storage }}
        cdnEndpoint: ${{ parameters.cdnEndpoint }}
        cdnProfile: ${{ parameters.cdnProfile }}

  # Deploy to PROD
  - ${{ if eq( variables['build.sourceBranch'], 'refs/heads/master') }}:
    - template: './stages/deploy-to-prod-stage.yml'
      parameters:
        storage: ${{ parameters.storage }}
        cdnEndpoint: ${{ parameters.cdnEndpoint }}
        cdnProfile: ${{ parameters.cdnProfile }}

