parameters:
  appName: ''
  packageFeed: ''
  storage: ''
  cdnEndpoint: ''
  cdnProfile: ''
  lokalise: true
  buildCommand: 'build --mode production'
  lokaliseCommand: 'lokalise --mode production'
  workingDir: ''
  distDir: ''
  isPullRequest: ''
  nodeJsVersion: ''
  appVersion: ''

stages:
  # Trigger before the build
  - template: './stages/pre-build-stage.yml'

  # Build the application and publish the artifact
  - template: './stages/build-stage.yml'
    parameters:
      packageFeed: ${{ parameters.packageFeed }}
      lokalise: ${{ parameters.lokalise }}
      lokaliseCommand: ${{ parameters.lokaliseCommand }}
      buildCommand: ${{ parameters.buildCommand }}
      workingDir: ${{ parameters.workingDir }}
      distDir: ${{ parameters.distDir }}
      nodeJsVersion: ${{ parameters.nodeJsVersion }}
      appVersion: ${{ parameters.appVersion }}

  # Trigger after the build
  - template: './stages/post-build-stage.yml'
    parameters:
      appName: ${{ parameters.appName }}
      packageFeed: ${{ parameters.packageFeed }}
      isPullRequest: ${{ parameters.isPullRequest }}
      nodeJsVersion: ${{ parameters.nodeJsVersion }}

  # Deploy to feature branch, dev, production
  - template: './stages/deploy-stage.yml'
    parameters:
      storage: ${{ parameters.storage }}
      cdnEndpoint: ${{ parameters.cdnEndpoint }}
      cdnProfile: ${{ parameters.cdnProfile }}
