import { mockBaseData } from '../base';
import { IOptionItem } from '../optionItem';
import {
  EFinancialAmountModes,
  EFinancialFrequency,
  IFinancialAssistanceTableItem,
  IFinancialAssistanceTableSubItem,
  IFinancialAssistanceTableMetadata,
  IFinancialAssistanceTableEntity,
  IFinancialAssistanceTableCombined,
  IFinancialAssistanceTableSubItemData,
  IFinancialAssistanceTableItemData,
} from './financial-assistance.types';

export const mockSubItems = (): IFinancialAssistanceTableSubItem[] => [
  {
    subCategory: {
      name: { translation: { en: "Children's Supplies", fr: 'Articles pour enfants' } },
      description: null,
      orderRank: 2,
      isOther: false,
      isDefault: false,
      id: '49860937-1bfd-4a1f-97ba-b7918afa4044',
      status: 1,
    },
    maximumAmount: 1,
    amountType: EFinancialAmountModes.Fixed,
    documentationRequired: false,
    frequency: EFinancialFrequency.OneTime,
  },
  {
    subCategory: {
      name: { translation: { en: 'Recreational Activity', fr: 'Activité récréative' } },
      description: null,
      orderRank: 3,
      isOther: false,
      isDefault: false,
      id: '1dfc68c5-4e7f-41c9-8106-afec0f4906c3',
      status: 1,
    },
    maximumAmount: 2,
    amountType: EFinancialAmountModes.Variable,
    documentationRequired: true,
    frequency: EFinancialFrequency.Multiple,
  },
];

export const mockSubItemData = (): IFinancialAssistanceTableSubItemData => ({
  subCategory: {
    optionItemId: 'optionItemId',
    specifiedOther: null,
  },
  maximumAmount: 1,
  amountType: EFinancialAmountModes.Fixed,
  documentationRequired: false,
  frequency: EFinancialFrequency.OneTime,
});

export const mockItems = (): IFinancialAssistanceTableItem[] => [
  {
    mainCategory: {
      name: { translation: { en: "Children's Needs", fr: "Besoins d'enfants" } },
      description: null,
      orderRank: 3,
      isOther: false,
      isDefault: false,
      subitems: [
        {
          name: { translation: { en: 'Child Care', fr: 'Service de gardiennage et de garderie' } },
          description: null,
          orderRank: 1,
          isOther: false,
          isDefault: false,
          id: '2cc4028b-88c5-42e6-8f44-3eb8c6781202',
          status: 1,
        },
        {
          name: { translation: { en: "Children's Supplies", fr: 'Articles pour enfants' } },
          description: null,
          orderRank: 2,
          isOther: false,
          isDefault: false,
          id: '49860937-1bfd-4a1f-97ba-b7918afa4044',
          status: 1,
        },
        {
          name: { translation: { en: 'Recreational Activity', fr: 'Activité récréative' } },
          description: null,
          orderRank: 3,
          isOther: false,
          isDefault: false,
          id: '1dfc68c5-4e7f-41c9-8106-afec0f4906c3',
          status: 1,
        },
      ],
      id: 'fab85d64-c242-48af-a893-46f91f6092b2',
      status: 1,
    },
    subItems: [
      {
        subCategory: {
          name: { translation: { en: "Children's Supplies", fr: 'Articles pour enfants' } },
          description: null,
          orderRank: 2,
          isOther: false,
          isDefault: false,
          id: '49860937-1bfd-4a1f-97ba-b7918afa4044',
          status: 1,
        },
        maximumAmount: 1,
        amountType: EFinancialAmountModes.Fixed,
        documentationRequired: false,
        frequency: EFinancialFrequency.OneTime,
      },
      {
        subCategory: {
          name: { translation: { en: 'Recreational Activity', fr: 'Activité récréative' } },
          description: null,
          orderRank: 3,
          isOther: false,
          isDefault: false,
          id: '1dfc68c5-4e7f-41c9-8106-afec0f4906c3',
          status: 1,
        },
        maximumAmount: 2,
        amountType: EFinancialAmountModes.Variable,
        documentationRequired: true,
        frequency: EFinancialFrequency.Multiple,
      },
    ],
  },
  {
    mainCategory: {
      name: { translation: { en: 'Household Goods', fr: 'Articles ménagers' } },
      description: null,
      orderRank: 8,
      isOther: false,
      isDefault: false,
      subitems: [
        {
          name: { translation: { en: 'Fridge Replacement', fr: 'Remplacement de réfrigérateur' } },
          description: null,
          orderRank: 1,
          isOther: false,
          isDefault: false,
          id: '438f1236-3018-4ee9-96a7-a7c367015c7e',
          status: 1,
        },
        {
          name: { translation: { en: 'Fridge Removal', fr: 'Retrait du réfrigérateur' } },
          description: null,
          orderRank: 2,
          isOther: false,
          isDefault: false,
          id: 'ccdd0fef-3ef2-41c0-931d-5da8c22e8d7c',
          status: 1,
        },
        {
          name: { translation: { en: 'Household Goods Replacement', fr: "Remplacement d'articles ménagers" } },
          description: null,
          orderRank: 3,
          isOther: false,
          isDefault: false,
          id: 'e943893a-8b5e-47f1-a46d-cfeb34fd9163',
          status: 1,
        },
        {
          name: { translation: { en: 'Storage/Moving', fr: 'Entreposage ou déménagement' } },
          description: null,
          orderRank: 4,
          isOther: false,
          isDefault: false,
          id: '7d05b919-2273-4268-b62d-9ac7895b83e2',
          status: 1,
        },
      ],
      id: 'cc8b8408-0d32-4535-80e4-ea5849fbe9e8',
      status: 1,
    },
    subItems: [
      {
        subCategory: {
          name: { translation: { en: 'Storage/Moving', fr: 'Entreposage ou déménagement' } },
          description: null,
          orderRank: 4,
          isOther: false,
          isDefault: false,
          id: '7d05b919-2273-4268-b62d-9ac7895b83e2',
          status: 1,
        },
        maximumAmount: 3,
        amountType: EFinancialAmountModes.Fixed,
        documentationRequired: false,
        frequency: EFinancialFrequency.OneTime,
      },
    ],
  },
];

export const mockItemData = (): IFinancialAssistanceTableItemData => ({
  mainCategory: {
    optionItemId: 'optionItemId',
    specifiedOther: null,
  },
  subItems: [mockSubItemData()],
});

export const mockFinancialAssistanceTableEntity = (): IFinancialAssistanceTableEntity => ({
  ...mockBaseData(),

  eventId: '8d88bc46-22c2-412d-814d-ff898357b745',
  programId: '657ae9a1-bfcc-4292-b871-8113b984e9cb',
  name: { translation: { en: 'abcd', fr: 'dcba' } },
  items: [
    {
      mainCategory: { optionItemId: '9b275d2f-00a1-4345-94fe-c37b84beb400', specifiedOther: null },
      subItems: [
        {
          subCategory: { optionItemId: '7eb37c59-4947-4edf-8146-c2458bd2b6f6', specifiedOther: null },
          maximumAmount: 1,
          amountType: EFinancialAmountModes.Fixed,
          documentationRequired: false,
          frequency: EFinancialFrequency.OneTime,
        },
      ],
    },
    {
      mainCategory: { optionItemId: '62421874-aed8-43bb-a668-bff1f45f08df', specifiedOther: null },
      subItems: [
        {
          subCategory: { optionItemId: '1d37919e-044e-44b9-99a4-d9a5f4fd5b13', specifiedOther: null },
          maximumAmount: 2,
          amountType: EFinancialAmountModes.Variable,
          documentationRequired: true,
          frequency: EFinancialFrequency.Multiple,
        },
        {
          subCategory: { optionItemId: '93897f29-c48d-414c-9dd7-d533759b32e6', specifiedOther: null },
          maximumAmount: 3,
          amountType: EFinancialAmountModes.Fixed,
          documentationRequired: false,
          frequency: EFinancialFrequency.OneTime,
        },
      ],
    },
  ],
});

export const mockCaseFinancialAssistanceEntities = () : IFinancialAssistanceTableEntity[] => ([
  mockFinancialAssistanceTableEntity(),
  mockFinancialAssistanceTableEntity(),
]);

export const mockFinancialAssistanceMetadata = (): IFinancialAssistanceTableMetadata => ({
  ...mockBaseData(),

  programId: '657ae9a1-bfcc-4292-b871-8113b984e9cb',
  programName: { translation: { en: 'abcd', fr: 'dcba' } },
  financialAssistanceTableStatusName: { translation: { en: 'status en', fr: 'status fr' } },
});

export const mockCombinedFinancialAssistance = (): IFinancialAssistanceTableCombined => ({
  entity: mockFinancialAssistanceTableEntity(),
  metadata: mockFinancialAssistanceMetadata(),
});

export const mockCombinedFinancialAssistances = (): IFinancialAssistanceTableCombined[] => ([mockCombinedFinancialAssistance()]);

const categories: IOptionItem[] = [
  {
    name: { translation: { en: 'Accommodation', fr: 'Hébergement' } },
    description: null,
    orderRank: 1,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Campground', fr: 'Terrain de camping' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: '75ffc95a-076e-417e-a1b9-c3466f6862bb',
        status: 1,
      },
      {
        name: { translation: { en: 'Hotel/Motel', fr: ' Hôtel ou motel' } },
        description: null,
        orderRank: 2,
        isOther: false,
        isDefault: false,
        id: 'f5b4b47a-1c9a-469d-94d1-86fcea98c60d',
        status: 1,
      },
      {
        name: { translation: { en: 'Family/Friends', fr: 'Parent ou amis' } },
        description: null,
        orderRank: 3,
        isOther: false,
        isDefault: false,
        id: 'e0b66d9e-eb59-4145-bba1-a41bab7e03ea',
        status: 1,
      },
      {
        name: { translation: { en: 'Insurance/Government Program Deductible', fr: "Franchises d'assurance ou de programme gouvernemental" } },
        description: null,
        orderRank: 4,
        isOther: false,
        isDefault: false,
        id: '3e135285-c7af-4ff9-8e4f-1b28c262b58d',
        status: 1,
      },
      {
        name: { translation: { en: 'Temporary Accommodation', fr: 'Hébergement temporaire' } },
        description: { translation: { en: '', fr: '' } },
        orderRank: 5,
        isOther: false,
        isDefault: false,
        id: '301a044f-79a9-4dde-9904-c30ba9207c05',
        status: 1,
      },
      {
        name: { translation: { en: 'Mortgage Assistance', fr: 'Aide hypothécaire' } },
        description: { translation: { en: '', fr: '' } },
        orderRank: 6,
        isOther: false,
        isDefault: false,
        id: '212565f3-6eb1-4dfc-adf5-4e23d26a4d47',
        status: 1,
      },
    ],
    id: 'e94d2922-699a-4aeb-b5f6-32015b134277',
    status: 1,
  },
  {
    name: { translation: { en: 'Basic Needs', fr: 'Besoins essentiels' } },
    description: null,
    orderRank: 2,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Basic Needs', fr: 'Besoins essentiels' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: '3b5afa60-b5af-4b32-ae7c-ddea729257e6',
        status: 1,
      },
      {
        name: { translation: { en: 'Supplement', fr: 'Supplément' } },
        description: null,
        orderRank: 2,
        isOther: false,
        isDefault: false,
        id: '6ba1fdc2-8d35-4620-ae99-4b3238614170',
        status: 1,
      },
    ],
    id: '6baa1ece-7ff5-4810-99b0-fdb0760da1f5',
    status: 1,
  },
  {
    name: { translation: { en: "Children's Needs", fr: "Besoins d'enfants" } },
    description: null,
    orderRank: 3,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Child Care', fr: 'Service de gardiennage et de garderie' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: '2cc4028b-88c5-42e6-8f44-3eb8c6781202',
        status: 1,
      },
      {
        name: { translation: { en: "Children's Supplies", fr: 'Articles pour enfants' } },
        description: null,
        orderRank: 2,
        isOther: false,
        isDefault: false,
        id: '49860937-1bfd-4a1f-97ba-b7918afa4044',
        status: 1,
      },
      {
        name: { translation: { en: 'Recreational Activity', fr: 'Activité récréative' } },
        description: null,
        orderRank: 3,
        isOther: false,
        isDefault: false,
        id: '1dfc68c5-4e7f-41c9-8106-afec0f4906c3',
        status: 1,
      },
    ],
    id: 'fab85d64-c242-48af-a893-46f91f6092b2',
    status: 1,
  },
  {
    name: { translation: { en: 'Clothing', fr: 'Habillement' } },
    description: null,
    orderRank: 4,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Laundry/Dry Cleaning', fr: 'Lessive ou nettoyage à sec' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: '631662f4-dd1f-4c28-bfe4-8574c9c326ff',
        status: 1,
      },
      {
        name: { translation: { en: 'Non-Winter Clothing', fr: 'Vêtements trois saisons' } },
        description: null,
        orderRank: 2,
        isOther: false,
        isDefault: false,
        id: '091694e9-10e0-48f5-b373-0cc7a881c508',
        status: 1,
      },
      {
        name: { translation: { en: 'Winter Clothing', fr: "Vêtements d'hiver" } },
        description: null,
        orderRank: 3,
        isOther: false,
        isDefault: false,
        id: 'b00e1f42-cb32-4226-a4cb-1554b411e534',
        status: 1,
      },
    ],
    id: '2bc00187-1583-42ec-a5f3-87e80a3ea29d',
    status: 1,
  },
  {
    name: { translation: { en: 'Exceptional', fr: 'Exception' } },
    description: null,
    orderRank: 5,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Exceptional', fr: 'Exception' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: '7eb37c59-4947-4edf-8146-c2458bd2b6f6',
        status: 1,
      },
    ],
    id: '9b275d2f-00a1-4345-94fe-c37b84beb400',
    status: 1,
  },
  {
    name: { translation: { en: 'Food', fr: 'Alimentation' } },
    description: null,
    orderRank: 6,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Groceries', fr: 'Épicerie' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: '2be81698-1a7d-4c42-870e-ee57dd260b49',
        status: 1,
      },
      {
        name: { translation: { en: 'Food Replacement', fr: "Remplacement d'aliments" } },
        description: null,
        orderRank: 2,
        isOther: false,
        isDefault: false,
        id: 'b428b299-1932-4beb-a6a3-391e48779df2',
        status: 1,
      },
      {
        name: { translation: { en: 'Infant Formula', fr: 'Lait maternisé' } },
        description: null,
        orderRank: 3,
        isOther: false,
        isDefault: false,
        id: 'c9e82f97-3f67-4fb7-90ad-663189813f41',
        status: 1,
      },
      {
        name: { translation: { en: 'Restaurant', fr: 'Restaurant' } },
        description: null,
        orderRank: 4,
        isOther: false,
        isDefault: false,
        id: '59643fce-7b7f-4006-8e74-c28adfd2f49a',
        status: 1,
      },
    ],
    id: '96febbda-2e4d-4868-a6c9-069715bd5a80',
    status: 1,
  },
  {
    name: { translation: { en: 'Health Services', fr: 'Services de santé' } },
    description: null,
    orderRank: 7,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Medical Equipment/Aids', fr: 'Équipement médical/Prothèses/matériel ambulatoire' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: '2328bec0-a92e-4c83-9aca-abbc323ae64a',
        status: 1,
      },
      {
        name: { translation: { en: 'Mental Health Needs', fr: 'Services de santé mentale' } },
        description: null,
        orderRank: 2,
        isOther: false,
        isDefault: false,
        id: '7ee8d431-f9bc-4cac-8295-7a7bffe2b7f9',
        status: 1,
      },
    ],
    id: '6067183b-d5c5-45ad-b370-c5bd22ec1a99',
    status: 1,
  },
  {
    name: { translation: { en: 'Household Goods', fr: 'Articles ménagers' } },
    description: null,
    orderRank: 8,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Fridge Replacement', fr: 'Remplacement de réfrigérateur' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: '438f1236-3018-4ee9-96a7-a7c367015c7e',
        status: 1,
      },
      {
        name: { translation: { en: 'Fridge Removal', fr: 'Retrait du réfrigérateur' } },
        description: null,
        orderRank: 2,
        isOther: false,
        isDefault: false,
        id: 'ccdd0fef-3ef2-41c0-931d-5da8c22e8d7c',
        status: 1,
      },
      {
        name: { translation: { en: 'Household Goods Replacement', fr: "Remplacement d'articles ménagers" } },
        description: null,
        orderRank: 3,
        isOther: false,
        isDefault: false,
        id: 'e943893a-8b5e-47f1-a46d-cfeb34fd9163',
        status: 1,
      },
      {
        name: { translation: { en: 'Storage/Moving', fr: 'Entreposage ou déménagement' } },
        description: null,
        orderRank: 4,
        isOther: false,
        isDefault: false,
        id: '7d05b919-2273-4268-b62d-9ac7895b83e2',
        status: 1,
      },
    ],
    id: 'cc8b8408-0d32-4535-80e4-ea5849fbe9e8',
    status: 1,
  },
  {
    name: { translation: { en: 'Land and Property', fr: 'Terrain et propriété' } },
    description: null,
    orderRank: 9,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Detached Structures', fr: 'Dépendances' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: '0eeb18a2-b473-485a-8ee9-71be84abb9cc',
        status: 1,
      },
      {
        name: { translation: { en: 'Debris Removal', fr: 'Ramassage des débris' } },
        description: null,
        orderRank: 2,
        isOther: false,
        isDefault: false,
        id: '1430ddf3-8498-41b5-9ca4-ac7164eb33c5',
        status: 1,
      },
      {
        name: { translation: { en: 'Fencing', fr: 'Clôture' } },
        description: null,
        orderRank: 3,
        isOther: false,
        isDefault: false,
        id: '6f86879f-600c-487c-8f4f-0c0cac85259a',
        status: 1,
      },
      {
        name: { translation: { en: 'Landscaping', fr: 'Aménagement du terrain' } },
        description: null,
        orderRank: 4,
        isOther: false,
        isDefault: false,
        id: 'ccd72f2e-351a-46c9-9ad9-1cda3f241434',
        status: 1,
      },
    ],
    id: 'bea6c244-73fc-49a3-a48b-c39a30d26924',
    status: 1,
  },
  {
    name: { translation: { en: 'Mass Assistance', fr: 'Aide à grande échelle' } },
    description: null,
    orderRank: 10,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Mass Assistance', fr: 'Aide à grande échelle' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: '596caa90-0b78-4d5e-b681-06b11d3d657e',
        status: 1,
      },
    ],
    id: '2134a6bf-385c-4d33-b02a-b84d41041104',
    status: 1,
  },
  {
    name: { translation: { en: 'Other', fr: 'Autre' } },
    description: null,
    orderRank: 11,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Specialized Services', fr: 'Services spécialisés' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: 'f8bae816-60e4-4b74-aec8-a028768a6885',
        status: 1,
      },
    ],
    id: '71659642-6cf0-4df9-9f0e-7c656e4cd9d2',
    status: 1,
  },
  {
    name: { translation: { en: 'Personal Services', fr: 'Services personnels' } },
    description: null,
    orderRank: 12,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Baby Products', fr: 'Articles pour bébé' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: '1d37919e-044e-44b9-99a4-d9a5f4fd5b13',
        status: 1,
      },
      {
        name: { translation: { en: 'Hygiene Products', fr: "Articles d'hygiène" } },
        description: null,
        orderRank: 2,
        isOther: false,
        isDefault: false,
        id: 'ac147c70-14cb-464b-a29f-faade1df6aad',
        status: 1,
      },
      {
        name: { translation: { en: 'Personal Care Supplies', fr: 'Articles de soins personnels' } },
        description: null,
        orderRank: 3,
        isOther: false,
        isDefault: false,
        id: '10a3cba5-cbf0-4b74-aa33-80556048288a',
        status: 1,
      },
      {
        name: { translation: { en: 'Prescriptions', fr: 'Ordonnances' } },
        description: null,
        orderRank: 4,
        isOther: false,
        isDefault: false,
        id: '93897f29-c48d-414c-9dd7-d533759b32e6',
        status: 1,
      },
    ],
    id: '62421874-aed8-43bb-a668-bff1f45f08df',

    status: 1,
  },
  {
    name: { translation: { en: 'Transportation', fr: 'Transport' } },
    description: null,
    orderRank: 14,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'Airfare/Train', fr: 'Avion ou train' } },
        description: null,
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: 'c61418b0-71e1-49ac-ab96-ee5cb2b3fd0a',
        status: 1,
      },
      {
        name: { translation: { en: 'Fuel/Mileage', fr: 'Carburant ou kilométrage' } },
        description: null,
        orderRank: 2,
        isOther: false,
        isDefault: false,
        id: 'd491e8cd-3011-4fb5-9d22-7f6270355d90',
        status: 1,
      },
      {
        name: { translation: { en: 'Local Transportation', fr: 'Transport local' } },
        description: null,
        orderRank: 3,
        isOther: false,
        isDefault: false,
        id: '77b8155d-1839-4219-96bb-7c0080abf04f',
        status: 1,
      },
      {
        name: { translation: { en: 'test-leo', fr: 'test-leo' } },
        description: { translation: { en: '', fr: '' } },
        orderRank: 4,
        isOther: false,
        isDefault: false,
        id: '4d881977-7195-41af-8e90-a22e08ebd5dd',
        status: 2,
      },
    ],
    id: '3bb2c441-5156-4880-90ac-0c2d4edb2df2',
    status: 1,
  },
  {
    name: { translation: { en: 'test', fr: 'test' } },
    description: { translation: { en: '', fr: '' } },
    orderRank: 15,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'aa', fr: 'aa' } },
        description: { translation: { en: '', fr: '' } },
        orderRank: 2,
        isOther: false,
        isDefault: false,
        id: 'b7b427c0-483a-4de6-bfad-b23dffe17feb',
        status: 2,
      },
      {
        name: { translation: { en: 'bb', fr: 'bb' } },
        description: { translation: { en: '', fr: '' } },
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: 'df794f6e-0888-40d5-aa7f-988ebf0954bc',
        status: 2,
      },
    ],
    id: '3beda5b4-2ec7-4886-a1d3-78c998880089',
    status: 1,
  },
  {
    name: { translation: { en: 'PO item name', fr: 'PO item name' } },
    description: { translation: { en: 'This is a description for the PO item', fr: 'This is a description for the PO item' } },
    orderRank: 17,
    isOther: false,
    isDefault: false,
    subitems: [
      {
        name: { translation: { en: 'PO sub-item1', fr: 'PO sub-item1' } },
        description: { translation: { en: 'This is a description for the sub-item1', fr: 'This is a description for the sub-item1' } },
        orderRank: 1,
        isOther: false,
        isDefault: false,
        id: 'ee610ae9-755e-4c70-83a5-112b0f03c015',
        status: 1,
      },
      {
        name: { translation: { en: 'PO sub-item2', fr: 'PO sub-item2' } },
        description: { translation: { en: 'This is a description for the sub-item2', fr: 'This is a description for the sub-item2' } },
        orderRank: 2,
        isOther: false,
        isDefault: false,
        id: 'a143ee62-f723-46fc-ae85-57c5662c61f4',
        status: 1,
      },
    ],
    id: '58c83ab1-cd27-4200-815a-f537e26f8201',
    status: 1,
  },
  {
    name: { translation: { en: 'Another PO item - EN', fr: 'Another PO item' } },
    description: { translation: { en: '', fr: '' } },
    orderRank: 19,
    isOther: false,
    isDefault: false,
    subitems: [],
    id: '4ec52b77-ce0d-43cb-a357-f52fe2b479cb',
    status: 1,
  },
];

export const mockCategories = (): IOptionItem[] => categories;
