parameters:
  nodeJsVersion: ''
  distDir: ''
  workingDir: ''
  parallelJobs: ''
  cypressSpec: ''
  displayName: ''


jobs:
  - job: Cypress
    pool:
      name: 'self-hosted-ubuntu-latest-fe' ## Need self-hosted to have static IP for security restrictions
    displayName: ${{ parameters.displayName }}
    variables:
      - group: Env-Dev
      - group: Cypress
    strategy:
      parallel: ${{ parameters.parallelJobs }}
    steps:
      - template: '../steps/cypress-steps.yml'
        parameters:
          packageFeed: ${{ parameters.packageFeed }}
          nodeJsVersion: ${{ parameters.nodeJsVersion }}
          distDir: ${{ parameters.distDir }}
          workingDir: ${{ parameters.workingDir }}
          cypressSpec: ${{ parameters.cypressSpec }}
