parameters:
  nodeJsVersion: ''
  distDir: ''
  workingDir: ''
  parallelJobs: ''
  cypressSpec: ''
  displayName: ''


jobs:
  - job: Cypress
    dependsOn: SetCypressRoleMode
    pool:
      name: 'self-hosted-ubuntu-latest-fe' ## Need self-hosted to have static IP for security restrictions
    displayName: ${{ parameters.displayName }}
    timeoutInMinutes: 180
    variables:
      - group: Env-Dev
      - group: Cypress
      - name: cypressAffectedTests
        value: $[ stageDependencies.FindCypressAffectedTestsStage.FindCypressAffectedTestsJob.outputs['getAffectedTests.affectedTests'] ]
      - name: cypressCanRoleMode
        value: $[ dependencies.SetCypressRoleMode.outputs['cypressRoleMode.CYPRESS_CAN_MODE'] ]
      - name: cypressCannotRoleMode
        value: $[ dependencies.SetCypressRoleMode.outputs['cypressRoleMode.CYPRESS_CANNOT_MODE'] ]
    strategy:
      parallel: ${{ parameters.parallelJobs }}
    steps:
      # If cypressAffectedTests is not null we use it, otherwise use the parameter cypressSpec.
      # The variable CYPRESS_SPEC will be used in the template cypress-steps.yml. It can't be passed as a parameter because it's generated after evaluation of template
      - script: |
          computedCypressSpec=$([ -n "$(cypressAffectedTests)" ] && echo "$(cypressAffectedTests)" || echo "${{ parameters.cypressSpec }}")
          echo "##vso[task.setvariable variable=CYPRESS_SPEC]$computedCypressSpec"

      - template: '../steps/cypress-steps.yml'
        parameters:
          packageFeed: ${{ parameters.packageFeed }}
          nodeJsVersion: ${{ parameters.nodeJsVersion }}
          distDir: ${{ parameters.distDir }}
          workingDir: ${{ parameters.workingDir }}
