parameters:
  packageFeed: ''
  nodeJsVersion: ''
  disableCache: ''
  distDir: ''
  workingDir: ''

jobs:
  - job: Cypress
    displayName: 'Critical path tests'
    variables:
      - group: Env-Dev
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      parallel: 2
    steps:
      - template: '../steps/cypress-steps.yml'
        parameters:
          packageFeed: ${{ parameters.packageFeed }}
          nodeJsVersion: ${{ parameters.nodeJsVersion }}
          disableCache: ${{ parameters.disableCache }}
          distDir: ${{ parameters.distDir }}
          workingDir: ${{ parameters.workingDir }}
