parameters:
  packageFeed: ''
  nodeJsVersion: ''
  distDir: ''
  workingDir: ''

jobs:
  - job: Cypress
    pool:
      name: 'self-hosted-ubuntu-latest-fe' ## Need self-hosted to have static IP for security restrictions
    displayName: 'Smoke tests'
    variables:
      - group: Env-Dev
      - group: Cypress
    strategy:
      parallel: 4
    steps:
      - template: '../steps/cypress-steps.yml'
        parameters:
          packageFeed: ${{ parameters.packageFeed }}
          nodeJsVersion: ${{ parameters.nodeJsVersion }}
          distDir: ${{ parameters.distDir }}
          workingDir: ${{ parameters.workingDir }}
          cypressSpec: 'cypress/e2e/smoke-tests/**/*.ts'
