parameters:
  job: ''
  jobDisplayName: ''
  scriptDisplayName: ''
  testKindParameter: ''
  packageFeed: ''
  nodeJsVersion: ''
  isPullRequest: ''
  appName: ''
  parallel: ''


jobs:
  - job: ${{ parameters.job }}
    strategy:
      parallel: ${{ parameters.parallel }}
    displayName: ${{ parameters.jobDisplayName }}
    steps:
      - template: '../steps/unit-tests-steps.yml'
        parameters:
          packageFeed: ${{ parameters.packageFeed }}
          nodeJsVersion:  ${{ parameters.nodeJsVersion }}
          scriptDisplayName: ${{ parameters.scriptDisplayName }}
          testKindParameter: ${{ parameters.testKindParameter }}
          isPullRequest: ${{ parameters.isPullRequest }}
          appName: ${{ parameters.appName }}
