import { ILeftMenuItem } from '@/types/interfaces/ILeftMenuItem';

export const tabs: ILeftMenuItem[] = [
  {
    id: 'privacy',
    labelKey: 'registration.menu.privacy',
    titleKey: 'registration.menu.privacy',
    icon: 'mdi-shield-check',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'PrivacyStatement',
  },
  {
    id: 'personalInfo',
    labelKey: 'registration.menu.personal_info',
    titleKey: 'registration.menu.personal_info',
    icon: 'mdi-account',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'PersonalInformation',
  },
  {
    id: 'addresses',
    labelKey: 'registration.menu.addresses',
    titleKey: 'registration.menu.addresses',
    icon: 'mdi-map-marker',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'Addresses',
  },
  {
    id: 'householdMembers',
    labelKey: 'registration.menu.household_members',
    titleKey: 'registration.menu.household_members',
    icon: 'mdi-account-multiple',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'HouseholdMembers',
  },
  {
    id: 'review',
    labelKey: 'registration.menu.review',
    titleKey: 'registration.menu.review',
    icon: 'mdi-file-search',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'registration.submit_registration.label',
    componentName: 'ReviewRegistration',
  },
  {
    id: 'confirmation',
    labelKey: 'registration.menu.confirmation',
    titleKey: 'registration.page.confirmation',
    icon: 'mdi-check',
    disabled: true,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.print',
    nextButtonTextKey: 'common.button.next',
    componentName: 'ConfirmRegistration',
  },
];
