//  Any lighten and darken variants not provided will still be generated by vuetify
// Please check https://vuetifyjs.com/en/customization/theme for more info

import colors from './colors';

export default {
  primary: colors.primary,
  secondary: colors.secondary,
  grey: colors.grey,
  status_error: colors.status.error,
  status_success: colors.status.success,
  status_warning: colors.status.warning,
  status_red_pale: colors.status.red_pale,
  status_green_pale: colors.status.green_pale,
  status_yellow_pale: colors.status.yellow_pale,
  status_grey_pale: colors.grey.lighten5,
  notification_error: colors.notifications.error,
  notification_success: colors.notifications.success,
  notification_warning: colors.notifications.warning,
  notification_info: colors.notifications.info,
  black: colors.black,
  white: colors.white,
};
