trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'apps/benef-app/*'

pool:
  name: 'self-hosted-ubuntu-latest'

variables:
- group: Build-Defaults
- name: Patch
  value: $[counter(format('{0}.{1}',variables['Major'],variables['Minor']),0)]
- name: cdnEndpoint
  value: 'emis-cdne-beneficiary'
- name: cdnProfile
  value: 'emis-cdnp-beneficiary'
- name: workingDir
  value: './apps/benef-app/'
- name: distDir
  value: './apps/benef-app/dist'
- name: appName
  value: 'benef-app'
- name: isPullRequest # Can't be used in condition
  value: $[eq(variables['Build.Reason'], 'PullRequest')]
- name: VUE_APP_VERSION
  value: $(Major).$(Minor).$(Patch)

name: Benef App - $(Major).$(Minor).$(Patch)


stages:
- template: '../../tools/pipelines/main.yml'
  parameters:
    appName: $(appName)
    storage: $(BeneficiaryWebAppStorage)
    packageFeed: $(PackageFeed-Npm)
    cdnEndpoint: $(cdnEndpoint)
    cdnProfile: $(cdnProfile)
    workingDir: $(workingDir)
    distDir: $(distDir)
    isPullRequest: $(isPullRequest)
