trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'apps/benef-app/*'

pool:
  name: 'self-hosted-ubuntu-latest'

variables:
- group: Build-Defaults
- name: Patch
  value: $[counter(format('{0}.{1}',variables['Major'],variables['Minor']),0)]
- name: cdnEndpoint
  value: 'emis-cdne-beneficiary'
- name: cdnProfile
  value: 'emis-cdnp-beneficiary'
- name: workingDir
  value: './apps/benef-app/'
- name: distDir
  value: './apps/benef-app/dist'
- name: appName
  value: 'benef-app'
- name: isPullRequest # Can't be used in condition
  value: $[eq(variables['Build.Reason'], 'PullRequest')]
- name: VITE_VERSION
  value: $(Major).$(Minor).$(Patch)
- name: nodeJsVersion
  value: '16.10.0'
- name: disableCache
  value: 'false' # change this value to force npm package to be installed
- name: browserStack
  value: 'false' # change this to activate browserstack for acceptance stage. The stage it
- name: testCommand
  ${{ if eq( variables.browserStack, 'true' ) }}:
    value: 'yarn test:browserstack --passWithNoTests --testPathPattern=apps/benef-app/tests/'
  ${{ else }}:
    value: 'yarn test:benef --passWithNoTests'


name: Benef App - $(Major).$(Minor).$(Patch)

resources:
  repositories:
    - repository: emisFrontEnd
      name: 'EMIS/crc-emis-frontend-tests'
      type: git
      ref: master

stages:
- template: '../../tools/pipelines/main.yml'
  parameters:
    appName: $(appName)
    storage: $(BeneficiaryWebAppStorage)
    packageFeed: $(PackageFeed-Npm)
    cdnEndpoint: $(cdnEndpoint)
    cdnProfile: $(cdnProfile)
    workingDir: $(workingDir)
    distDir: $(distDir)
    isPullRequest: $(isPullRequest)
    nodeJsVersion: $(nodeJsVersion)
    disableCache: $(disableCache)
    testCommand: $(testCommand)
