trigger:
  branches:
    include:
    - master
  paths:
    include:
    - apps/benef-app/*
    exclude:
    - apps/benef-app/cypress/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Build-Defaults
- name: Patch
  value: $[counter(format('{0}.{1}',variables['Major'],variables['Minor']),0)]
- name: cdnEndpoint
  value: 'emis-cdne-beneficiary'
- name: cdnProfile
  value: 'emis-cdnp-beneficiary'
- name: workingDir
  value: './apps/benef-app/'
- name: distDir
  value: './apps/benef-app/dist'
- name: appName
  value: 'benef-app'
- name: isPullRequest # Can't be used in condition
  value: $[eq(variables['Build.Reason'], 'PullRequest')]
- name: VITE_VERSION
  value: $(Major).$(Minor).$(Patch)
- name: nodeJsVersion
  value: '18.20.4' # use a cache version from the ubuntu-latest image, so we don't have errors when downloading https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md
- name: disableCache
  value: 'false' # change this value to force npm package to be installed

name: Benef App - $(Major).$(Minor).$(Patch)

stages:
- template: '../../tools/pipelines/main.yml'
  parameters:
    appName: $(appName)
    storage: $(BeneficiaryWebAppStorage)
    packageFeed: $(PackageFeed-Npm)
    cdnEndpoint: $(cdnEndpoint)
    cdnProfile: $(cdnProfile)
    workingDir: $(workingDir)
    distDir: $(distDir)
    isPullRequest: $(isPullRequest)
    nodeJsVersion: $(nodeJsVersion)
    disableCache: $(disableCache)
    parallelJobsSmokeTests: 1
    verifyPipelinesIds: "287,299" ## Ids of pipeline we want to verify before pushing to PROD
    verifyBuildAgeLimit: 3