trigger:
  branches:
    include:
      - master
  paths:
    include:
      - apps/emis-app/cypress/e2e/critical-path-tests/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Build-Defaults
  - name: Patch
    value: $[counter(format('{0}.{1}',variables['Major'],variables['Minor']),0)]
  - name: workingDir
    value: './apps/emis-app/'
  - name: distDir
    value: './apps/emis-app/dist'
  - name: VITE_VERSION
    value: $(Major).$(Minor).$(Patch)
  - name: nodeJsVersion
    value: '18.20.4' # use a cache version from the ubuntu-latest image, so we don't have errors when downloading https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md
  - name: disableCache
    value: 'false' # change this value to force npm package to be installed

name: Critical Path - EMIS App - $(Major).$(Minor).$(Patch)

stages:
  - template: '../../tools/pipelines/critical-path-tests.yml'
    parameters:
      appVersion: $(VITE_VERSION)
      packageFeed: $(PackageFeed-Npm)
      workingDir: $(workingDir)
      distDir: $(distDir)
      nodeJsVersion: $(nodeJsVersion)
      disableCache: $(disableCache)
      parallelJobs: 3
