trigger:
  branches:
    include:
    - master
  paths:
    include:
    - apps/emis-app/*
    exclude:
    - apps/emis-app/cypress/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Build-Defaults
- name: Patch
  value: $[counter(format('{0}.{1}',variables['Major'],variables['Minor']),0)]
- name: cdnEndpoint
  value: 'emis-cdne-emis'
- name: cdnProfile
  value: 'emis-cdnp-emis'
- name: workingDir
  value: './apps/emis-app/'
- name: distDir
  value: './apps/emis-app/dist'
- name: appName
  value: 'emis-app'
- name: isPullRequest # Can't be used in condition
  value: $[eq(variables['Build.Reason'], 'PullRequest')]
- name: VITE_VERSION
  value: $(Major).$(Minor).$(Patch)
- name: nodeJsVersion
  value: '16.10.0'
- name: disableCache
  value: 'false' # change this value to force npm package to be installed

name: EMIS App - $(Major).$(Minor).$(Patch)

stages:
- template: '../../tools/pipelines/main.yml'
  parameters:
    appName: $(appName)
    storage: $(EmisWebAppStorage)
    packageFeed: $(PackageFeed-Npm)
    cdnEndpoint: $(cdnEndpoint)
    cdnProfile: $(cdnProfile)
    workingDir: $(workingDir)
    distDir: $(distDir)
    isPullRequest: $(isPullRequest)
    nodeJsVersion: $(nodeJsVersion)
    appVersion: $(VITE_VERSION)
    disableCache: $(disableCache)
    parallelJobsSmokeTests: 4
