trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'apps/emis-app/*'

pool:
  name: 'self-hosted-ubuntu-latest'

variables:
- group: Build-Defaults
- name: Patch
  value: $[counter(format('{0}.{1}',variables['Major'],variables['Minor']),0)]
- name: cdnEndpoint
  value: 'emis-cdne-emis'
- name: cdnProfile
  value: 'emis-cdnp-emis'
- name: workingDir
  value: './apps/emis-app/'
- name: distDir
  value: './apps/emis-app/dist'

name: EMIS App - $(Major).$(Minor).$(Patch)


stages:
- template: '../../tools/pipelines/stages/deploy-vue-stage.yml'
  parameters:
    storage: $(EmisWebAppStorage)
    packageFeed: $(PackageFeed-Npm)
    cdnEndpoint: $(cdnEndpoint)
    cdnProfile: $(cdnProfile)
    workingDir: $(workingDir)
    distDir: $(distDir)
