trigger:
  branches:
    include:
      - master
  paths:
    include:
      - apps/emis-app/cypress/e2e/smoke-tests/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Build-Defaults
  - name: Patch
    value: $[counter(format('{0}.{1}',variables['Major'],variables['Minor']),0)]
  - name: workingDir
    value: './apps/emis-app/'
  - name: distDir
    value: './apps/emis-app/dist'
  - name: VITE_VERSION
    value: $(Major).$(Minor).$(Patch)
  - name: nodeJsVersion
    value: '16.10.0'
  - name: disableCache
    value: 'false' # change this value to force npm package to be installed

name: Smoke Tests - EMIS App - $(Major).$(Minor).$(Patch)

stages:
  - template: '../../tools/pipelines/smoke-tests.yml'
    parameters:
      appVersion: $(VITE_VERSION)
      packageFeed: $(PackageFeed-Npm)
      workingDir: $(workingDir)
      distDir: $(distDir)
      nodeJsVersion: $(nodeJsVersion)
      disableCache: $(disableCache)
      parallelJobs: 4
