import { IRegistrationMenuItem } from '../../../types';

export const mockTabs = (): IRegistrationMenuItem[] => [
  {
    id: 'privacy',
    labelKey: 'registration.menu.privacy',
    titleKey: 'registration.menu.privacy',
    icon: '',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'PrivacyStatement',
    helpLink: '',
  },
  {
    id: 'personalInfo',
    labelKey: 'registration.menu.personal_info',
    titleKey: 'registration.menu.personal_info',
    icon: '',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'PersonalInformation',
    helpLink: '',
  },
  {
    id: 'addresses',
    labelKey: 'registration.menu.addresses',
    titleKey: 'registration.menu.addresses',
    icon: '',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'Addresses',
    helpLink: '',
  },
  {
    id: 'additionalMembers',
    labelKey: 'registration.menu.household_members',
    titleKey: 'registration.menu.household_members',
    icon: '',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'common.button.next',
    componentName: 'AdditionalMembers',
    helpLink: '',
  },
  {
    id: 'review',
    labelKey: 'registration.menu.review',
    titleKey: 'registration.menu.review',
    icon: '',
    disabled: false,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.back',
    nextButtonTextKey: 'registration.submit_registration.label',
    componentName: 'ReviewRegistration',
    helpLink: '',
  },
  {
    id: 'confirmation',
    labelKey: 'registration.menu.confirmation',
    titleKey: 'registration.page.confirmation',
    icon: '',
    disabled: true,
    isValid: true,
    isTouched: false,
    backButtonTextKey: 'common.button.print',
    nextButtonTextKey: 'common.button.next',
    componentName: 'ConfirmRegistration',
    helpLink: '',
  },
];
