import { IStorageMock } from './storage.types';

export const mockStorageFinancialAssistance = () : IStorageMock => ({
  getters: {
    name: jest.fn(),
    program: jest.fn(),
    status: jest.fn(),
    addingItem: jest.fn(),
    items: jest.fn(),
    subItems: jest.fn(),
    newItem: jest.fn(),
    editedItem: jest.fn(),
    editedItemIndex: jest.fn(),
    editedSubItemIndex: jest.fn(),
    newSubItem: jest.fn(),
    dirty: jest.fn(),
    formDirty: jest.fn(),
    loading: jest.fn(),
    isOperating: jest.fn(),
  },

  mutations: {
    setId: jest.fn(),
    setName: jest.fn(),
    setNameInAllLanguages: jest.fn(),
    setStatus: jest.fn(),
    setAddingItem: jest.fn(),
    setProgram: jest.fn(),
    setItems: jest.fn(),
    setItem: jest.fn(),
    setItemItem: jest.fn(),
    setSubItem: jest.fn(),
    setSubItemSubItem: jest.fn(),
    setSubItemMaximum: jest.fn(),
    setSubItemAmountType: jest.fn(),
    setSubItemDocumentationRequired: jest.fn(),
    setSubItemFrequency: jest.fn(),
    setNewItemItem: jest.fn(),
    setNewSubItem: jest.fn(),
    setNewSubItemSubItem: jest.fn(),
    setNewSubItemMaximum: jest.fn(),
    setNewSubItemAmountType: jest.fn(),
    setNewSubItemDocumentationRequired: jest.fn(),
    setNewSubItemFrequency: jest.fn(),
    addItem: jest.fn(),
    addSubItem: jest.fn(),
    setItemSubItems: jest.fn(),
    setEditedItem: jest.fn(),
    setEditedItemIndex: jest.fn(),
    setEditedSubItemIndex: jest.fn(),
    deleteItem: jest.fn(),
    deleteSubItem: jest.fn(),
    setDirty: jest.fn(),
    setFormDirty: jest.fn(),
    setLoading: jest.fn(),
    resetNewItem: jest.fn(),
    resetNewSubItem: jest.fn(),
    resetState: jest.fn(),
    cancelOperation: jest.fn(),
  },

  actions: {
    createFinancialAssistance: jest.fn(),
    fetchActiveCategories: jest.fn(),
  },
});
